name:  " Simple Github Actions Workflow"
on:
  push:
    branches:
      - master
  

jobs:

  build:
  
    runs-on:  ubuntu-latest
    
    steps:
      -  name: "running date command"
         run: date
         shell: bash
      
      -  name: "User details"
         run: whoami
         shell: bash
      
      -  name: "Deatils of OS"
         run: cat /etc/os-release
         shell: bash
     
      -  name: "current working directory before checkout"
         run: |
           pwd
           ls -al
      

      -  name: "checkout Repository"
         uses: actions/checkout@v3
      

      -  name: "current working directory after checkout"
         run: |
           pwd
           ls -al
      
      -  name: "Installing terraform"
         run:  |
           wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
           unzip terraform_1.6.6_linux_amd64.zip
           ./terraform version
            ls -al
      
      -  name: "Running script.sh"
         run: |
           chmod +x script.sh
           ./script.sh  
